controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    # Fallback route to handle undefined routes
    #fallback_route:
    #   path: /{url}
    #   controller: App\Controller\ErrorController::routeNotFound
    #   requirements:
    #       url: ".+"