parameters:
    artwork_images_directory: '%kernel.project_dir%/public/uploads/artworks'
    raffle_images_directory: '%kernel.project_dir%/public/uploads/raffle_images'
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    evidence_directory: '%kernel.project_dir%/public/uploads/evidence'
    blog_images_directory: '%kernel.project_dir%/public/uploads/blog_images'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    recaptcha_secret: '%env(RECAPTCHA_SECRET)%'
    app.recaptcha_secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    etherscan.api_url: 'https://api-sepolia.etherscan.io/api'
    etherscan.api_key: '%env(ETHERSCAN_API_KEY)%'
    etherscan.contract_address: '0x44Ab62a8DFC2d8403E27F4b85717Cc3b986d1801'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%artwork_images_directory%'

    App\Service\EthereumService:
        arguments: []

    App\Twig\EthereumExtension:
        tags: ['twig.extension']
        arguments:
            $ethereumService: '@App\Service\EthereumService'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\EtherscanService:
        arguments:
            $httpClient: '@http_client'
            $apiUrl: '%etherscan.api_url%'
            $apiKey: '%etherscan.api_key%'
            $contractAddress: '%etherscan.contract_address%'
            $logger: '@logger'

    App\Service\PasswordResetService:
        arguments:
            $mailer: '@mailer'
            $entityManager: '@doctrine.orm.entity_manager'

    App\Form\RecaptchaType:
        arguments:
            $siteKey: '%google_recaptcha_site_key%'

    App\Controller\RaffleController:
        arguments:
            $recaptchaSecret: '%app.recaptcha_secret%'

    App\Service\GeminiService:
        arguments:
            $httpClient: '@http_client'
            $geminiApiKey: '%env(GEMINI_API_KEY)%'
            $entityManager: '@doctrine.orm.entity_manager'


    App\Service\ProfanityFilter:
        autowire: true
