parameters:
    artwork_images_directory: '%kernel.project_dir%/public/uploads/artworks'
    raffle_images_directory: '%kernel.project_dir%/public/uploads/raffle_images'
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    evidence_directory: '%kernel.project_dir%/public/uploads/evidence'
    blog_images_directory: '%kernel.project_dir%/public/uploads/blog_images'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    recaptcha_secret: '%env(RECAPTCHA_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%artwork_images_directory%'

    App\Service\EthereumService:
        arguments: []

    App\Twig\EthereumExtension:
        tags: ['twig.extension']
        arguments:
            $ethereumService: '@App\Service\EthereumService'

    App\Form\RecaptchaType:
        arguments:
            $siteKey: '%google_recaptcha_site_key%'